param(
  [string]$RepoPath = (Join-Path "$env:USERPROFILE\Desktop" "observer-ci-lab")
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

function Write-File([string]$Path, [string[]]$Lines) {
  $dir = Split-Path -Parent $Path
  if ($dir -and -not (Test-Path $dir)) { New-Item -ItemType Directory -Path $dir -Force | Out-Null }
  $Lines | Set-Content -Encoding UTF8 -Path $Path
}

Write-Host "Repo path: $RepoPath"
if (-not (Test-Path $RepoPath)) { New-Item -ItemType Directory -Path $RepoPath -Force | Out-Null }
Set-Location $RepoPath

# folders
New-Item -ItemType Directory -Path ".github\workflows" -Force | Out-Null
New-Item -ItemType Directory -Path "trading" -Force | Out-Null
New-Item -ItemType Directory -Path "tests" -Force | Out-Null

# requirements.txt
Write-File ".\requirements.txt" @(
  "pytest",
  "coverage",
  "pandas",
  "numpy"
)

# pyproject.toml
Write-File ".\pyproject.toml" @(
  "[tool.pytest.ini_options]",
  'testpaths = ["tests"]',
  'addopts = "-q"',
  "",
  "[tool.coverage.run]",
  'source = ["trading"]',
  "branch = false",
  "",
  "[tool.coverage.report]",
  "show_missing = true",
  "skip_empty = true"
)

# GitHub Actions workflow
Write-File ".\.github\workflows\ci.yml" @(
  "name: CI Pipeline",
  "on: [push, pull_request]",
  "jobs:",
  "  test:",
  "    runs-on: ubuntu-latest",
  "    steps:",
  "      - uses: actions/checkout@v4",
  "      - uses: actions/setup-python@v5",
  "        with:",
  '          python-version: "3.11"',
  "      - run: pip install -r requirements.txt",
  "      - run: coverage run -m pytest -q",
  "      - run: coverage report --fail-under=90"
)

# README.md (no backticks)
Write-File ".\README.md" @(
  "# observer-ci-lab",
  "",
  "Minimal Observer-pattern market data -> observers -> broker engine, with pytest + coverage + GitHub Actions.",
  "",
  "Run locally:",
  "  pip install -r requirements.txt",
  "  pytest",
  "  coverage run -m pytest",
  "  coverage report -m",
  "",
  "CI:",
  "GitHub Actions runs tests + coverage and fails if coverage < 90%."
)

# trading/__init__.py
Write-File ".\trading\__init__.py" @(
  "__all__ = [",
  '    "MarketDataSubject",',
  '    "Observer",',
  '    "VolatilityBreakoutStrategyObserver",',
  '    "RiskObserver",',
  '    "LoggerObserver",',
  '    "Broker",',
  '    "Engine",',
  "]",
  "",
  "from .subject import MarketDataSubject, Observer",
  "from .observers import VolatilityBreakoutStrategyObserver, RiskObserver, LoggerObserver",
  "from .broker import Broker",
  "from .engine import Engine"
)

# trading/subject.py
Write-File ".\trading\subject.py" @(
  "from __future__ import annotations",
  "",
  "from dataclasses import dataclass",
  "from typing import Protocol, List, Iterable",
  "",
  "",
  "class Observer(Protocol):",
  "    def update(self, price: float) -> None:",
  "        ...",
  "",
  "",
  "@dataclass(frozen=True)",
  "class NotificationError(Exception):",
  "    observer: object",
  "    original: Exception",
  "",
  "    def __str__(self) -> str:",
  "        return f""Observer {self.observer!r} raised {self.original!r}""",
  "",
  "",
  "class MarketDataSubject:",
  "    def __init__(self, *, continue_on_error: bool = False):",
  "        self._observers: List[Observer] = []",
  "        self._continue_on_error = continue_on_error",
  "",
  "    @property",
  "    def observers(self) -> Iterable[Observer]:",
  "        return tuple(self._observers)",
  "",
  "    def attach(self, observer: Observer) -> None:",
  "        if observer not in self._observers:",
  "            self._observers.append(observer)",
  "",
  "    def detach(self, observer: Observer) -> None:",
  "        try:",
  "            self._observers.remove(observer)",
  "        except ValueError:",
  "            return",
  "",
  "    def notify(self, price: float) -> None:",
  "        errors: list[NotificationError] = []",
  "        for obs in list(self._observers):",
  "            try:",
  "                obs.update(price)",
  "            except Exception as e:",
  "                if not self._continue_on_error:",
  "                    raise",
  "                errors.append(NotificationError(obs, e))",
  "        if errors:",
  "            raise errors[0]"
)

# trading/observers.py
Write-File ".\trading\observers.py" @(
  "from __future__ import annotations",
  "",
  "import math",
  "from dataclasses import dataclass",
  "from typing import Optional, Any",
  "",
  "import numpy as np",
  "import pandas as pd",
  "",
  "",
  "class VolatilityBreakoutStrategyObserver:",
  "    def __init__(self, window: int = 20):",
  "        if window < 2:",
  "            raise ValueError(""window must be >= 2"")",
  "        self.window = int(window)",
  "        self._prices: list[float] = []",
  "        self._last_signal: int = 0",
  "",
  "    def update(self, price: float) -> None:",
  "        if not isinstance(price, (int, float)) or not math.isfinite(float(price)):",
  "            self._last_signal = 0",
  "            return",
  "",
  "        p = float(price)",
  "        self._prices.append(p)",
  "",
  "        if len(self._prices) < 2:",
  "            self._last_signal = 0",
  "            return",
  "",
  "        prices = np.asarray(self._prices, dtype=float)",
  "        returns = prices[1:] / prices[:-1] - 1.0",
  "",
  "        if returns.size <= self.window:",
  "            self._last_signal = 0",
  "            return",
  "",
  "        last_r = float(returns[-1])",
  "        prev_window = returns[-(self.window + 1) : -1]",
  "        sigma = float(np.std(prev_window, ddof=1)) if prev_window.size >= 2 else 0.0",
  "",
  "        if sigma <= 0.0:",
  "            self._last_signal = 0",
  "        elif last_r > sigma:",
  "            self._last_signal = 1",
  "        elif last_r < -sigma:",
  "            self._last_signal = -1",
  "        else:",
  "            self._last_signal = 0",
  "",
  "    @property",
  "    def last_signal(self) -> int:",
  "        return self._last_signal",
  "",
  "    @property",
  "    def prices(self) -> tuple[float, ...]:",
  "        return tuple(self._prices)",
  "",
  "",
  "class RiskObserver:",
  "    def __init__(self, max_position: int, broker: Any):",
  "        if max_position < 0:",
  "            raise ValueError(""max_position must be >= 0"")",
  "        self.max_position = int(max_position)",
  "        self._broker = broker",
  "        self.breached = False",
  "        self.last_price: Optional[float] = None",
  "",
  "    def update(self, price: float) -> None:",
  "        self.last_price = float(price)",
  "        pos = int(getattr(self._broker, ""position""))",
  "        if abs(pos) > self.max_position:",
  "            self.breached = True",
  "",
  "",
  "@dataclass",
  "class LogRecord:",
  "    price: float",
  "    signal: Optional[int]",
  "",
  "",
  "class LoggerObserver:",
  "    def __init__(self, strategy: Optional[Any] = None):",
  "        self._strategy = strategy",
  "        self.prices: list[float] = []",
  "        self.records: list[LogRecord] = []",
  "",
  "    def update(self, price: float) -> None:",
  "        p = float(price)",
  "        self.prices.append(p)",
  "        sig: Optional[int] = None",
  "        if self._strategy is not None and hasattr(self._strategy, ""last_signal""):",
  "            sig = int(getattr(self._strategy, ""last_signal""))",
  "        self.records.append(LogRecord(price=p, signal=sig))",
  "",
  "    def to_frame(self) -> pd.DataFrame:",
  "        return pd.DataFrame([{""price"": r.price, ""signal"": r.signal} for r in self.records])"
)

# trading/broker.py
Write-File ".\trading\broker.py" @(
  "from __future__ import annotations",
  "",
  "",
  "class Broker:",
  "    def __init__(self, cash: float = 1_000_000):",
  "        if cash < 0:",
  "            raise ValueError(""cash must be nonnegative"")",
  "        self.cash = float(cash)",
  "        self.position = 0",
  "",
  "    def market_order(self, side: str, qty: int, price: float) -> None:",
  "        if side not in (""buy"", ""sell""):",
  "            raise ValueError(""side must be 'buy' or 'sell'"")",
  "        if not isinstance(qty, int) or qty <= 0:",
  "            raise ValueError(""qty must be a positive int"")",
  "        if not isinstance(price, (int, float)) or price <= 0:",
  "            raise ValueError(""price must be positive"")",
  "",
  "        cost = float(qty) * float(price)",
  "",
  "        if side == ""buy"":",
  "            if self.cash < cost:",
  "                raise ValueError(""insufficient cash"")",
  "            self.cash -= cost",
  "            self.position += qty",
  "        else:",
  "            if self.position < qty:",
  "                raise ValueError(""insufficient shares"")",
  "            self.position -= qty",
  "            self.cash += cost",
  "",
  "    def equity(self, last_price: float) -> float:",
  "        if not isinstance(last_price, (int, float)) or last_price <= 0:",
  "            raise ValueError(""last_price must be positive"")",
  "        return float(self.cash) + float(self.position) * float(last_price)"
)

# trading/engine.py
Write-File ".\trading\engine.py" @(
  "from __future__ import annotations",
  "",
  "import pandas as pd",
  "",
  "from .subject import MarketDataSubject",
  "from .broker import Broker",
  "",
  "",
  "class Engine:",
  "    def __init__(self, subject: MarketDataSubject, strategy, broker: Broker, *, trade_qty: int = 1):",
  "        if trade_qty <= 0:",
  "            raise ValueError(""trade_qty must be positive"")",
  "        self.subject = subject",
  "        self.strategy = strategy",
  "        self.broker = broker",
  "        self.trade_qty = int(trade_qty)",
  "",
  "        self.subject.attach(self.strategy)",
  "",
  "    def run(self, prices: pd.Series) -> float:",
  "        if len(prices) == 0:",
  "            raise ValueError(""prices is empty"")",
  "",
  "        last_price = None",
  "        for x in prices:",
  "            p = float(x)",
  "            last_price = p",
  "",
  "            self.subject.notify(p)",
  "",
  "            sig = int(getattr(self.strategy, ""last_signal""))",
  "            if sig == 1:",
  "                self.broker.market_order(""buy"", self.trade_qty, p)",
  "            elif sig == -1:",
  "                self.broker.market_order(""sell"", self.trade_qty, p)",
  "",
  "        return self.broker.equity(float(last_price))"
)

# tests/conftest.py
Write-File ".\tests\conftest.py" @(
  "import numpy as np",
  "import pandas as pd",
  "import pytest",
  "",
  "from trading.subject import MarketDataSubject",
  "from trading.observers import VolatilityBreakoutStrategyObserver, LoggerObserver",
  "from trading.broker import Broker",
  "",
  "",
  "@pytest.fixture",
  "def prices():",
  "    return pd.Series(np.linspace(100, 120, 200))",
  "",
  "@pytest.fixture",
  "def subject():",
  "    return MarketDataSubject()",
  "",
  "@pytest.fixture",
  "def subject_continue():",
  "    return MarketDataSubject(continue_on_error=True)",
  "",
  "@pytest.fixture",
  "def strategy():",
  "    return VolatilityBreakoutStrategyObserver(window=20)",
  "",
  "@pytest.fixture",
  "def logger():",
  "    return LoggerObserver()",
  "",
  "@pytest.fixture",
  "def broker():",
  "    return Broker(cash=1_000)"
)

# tests/test_subject.py
Write-File ".\tests\test_subject.py" @(
  "import pytest",
  "from unittest.mock import MagicMock",
  "",
  "from trading.subject import MarketDataSubject, NotificationError",
  "",
  "",
  "def test_attach_avoids_duplicates():",
  "    subject = MarketDataSubject()",
  "    obs = MagicMock()",
  "    subject.attach(obs)",
  "    subject.attach(obs)",
  "    assert list(subject.observers) == [obs]",
  "",
  "",
  "def test_attach_and_notify_calls_update_once():",
  "    subject = MarketDataSubject()",
  "    obs = MagicMock()",
  "    subject.attach(obs)",
  "    subject.notify(101.0)",
  "    obs.update.assert_called_once_with(101.0)",
  "",
  "",
  "def test_detach_is_idempotent():",
  "    subject = MarketDataSubject()",
  "    obs = MagicMock()",
  "    subject.detach(obs)",
  "    subject.attach(obs)",
  "    subject.detach(obs)",
  "    subject.detach(obs)",
  "",
  "",
  "def test_detach_stops_notifications():",
  "    subject = MarketDataSubject()",
  "    obs = MagicMock()",
  "    subject.attach(obs)",
  "    subject.detach(obs)",
  "    subject.notify(101.0)",
  "    obs.update.assert_not_called()",
  "",
  "",
  "def test_notify_preserves_order():",
  "    subject = MarketDataSubject()",
  "    calls = []",
  "",
  "    class A:",
  "        def update(self, price: float) -> None:",
  "            calls.append(('A', price))",
  "",
  "    class B:",
  "        def update(self, price: float) -> None:",
  "            calls.append(('B', price))",
  "",
  "    subject.attach(A())",
  "    subject.attach(B())",
  "    subject.notify(5.0)",
  "    assert calls == [('A', 5.0), ('B', 5.0)]",
  "",
  "",
  "def test_notify_propagates_error_by_default():",
  "    subject = MarketDataSubject()",
  "    good = MagicMock()",
  "",
  "    class Bad:",
  "        def update(self, price: float) -> None:",
  "            raise RuntimeError('boom')",
  "",
  "    subject.attach(Bad())",
  "    subject.attach(good)",
  "",
  "    with pytest.raises(RuntimeError):",
  "        subject.notify(1.0)",
  "",
  "    good.update.assert_not_called()",
  "",
  "",
  "def test_notify_continue_on_error_notifies_all(subject_continue):",
  "    subject = subject_continue",
  "    good = MagicMock()",
  "",
  "    class Bad:",
  "        def update(self, price: float) -> None:",
  "            raise RuntimeError('boom')",
  "",
  "    subject.attach(Bad())",
  "    subject.attach(good)",
  "",
  "    with pytest.raises(NotificationError):",
  "        subject.notify(1.0)",
  "",
  "    good.update.assert_called_once_with(1.0)"
)

# tests/test_observers.py
Write-File ".\tests\test_observers.py" @(
  "from trading.observers import VolatilityBreakoutStrategyObserver, LoggerObserver, RiskObserver",
  "from trading.broker import Broker",
  "",
  "",
  "def test_logger_records_all_prices(subject, logger, prices):",
  "    subject.attach(logger)",
  "    for p in prices:",
  "        subject.notify(float(p))",
  "    assert logger.prices[0] == float(prices.iloc[0])",
  "    assert len(logger.prices) == len(prices)",
  "",
  "",
  "def test_logger_can_record_signals():",
  "    s = VolatilityBreakoutStrategyObserver(window=5)",
  "    log = LoggerObserver(strategy=s)",
  "    s.update(100.0)",
  "    log.update(100.0)",
  "    assert log.records[-1].signal == 0",
  "",
  "",
  "def test_strategy_emits_zero_until_enough_data():",
  "    s = VolatilityBreakoutStrategyObserver(window=5)",
  "    for p in [100, 101, 102, 103, 104, 105, 106]:",
  "        s.update(float(p))",
  "    assert s.last_signal in (-1, 0, 1)",
  "",
  "",
  "def test_strategy_handles_constant_prices_as_zero():",
  "    s = VolatilityBreakoutStrategyObserver(window=5)",
  "    for _ in range(30):",
  "        s.update(100.0)",
  "        assert s.last_signal == 0",
  "",
  "",
  "def test_strategy_ignores_nan_and_sets_zero():",
  "    s = VolatilityBreakoutStrategyObserver(window=5)",
  "    s.update(100.0)",
  "    s.update(float('nan'))",
  "    assert s.last_signal == 0",
  "    assert s.prices == (100.0,)",
  "",
  "",
  "def test_risk_observer_flags_breach():",
  "    b = Broker(cash=1_000)",
  "    r = RiskObserver(max_position=2, broker=b)",
  "    r.update(100.0)",
  "    assert r.breached is False",
  "    b.position = 3",
  "    r.update(101.0)",
  "    assert r.breached is True"
)

# tests/test_broker.py
Write-File ".\tests\test_broker.py" @(
  "import pytest",
  "from trading.broker import Broker",
  "",
  "",
  "def test_buy_updates_cash_and_position():",
  "    b = Broker(cash=100.0)",
  "    b.market_order('buy', 2, 10.0)",
  "    assert b.position == 2",
  "    assert b.cash == 80.0",
  "",
  "",
  "def test_sell_updates_cash_and_position():",
  "    b = Broker(cash=100.0)",
  "    b.market_order('buy', 2, 10.0)",
  "    b.market_order('sell', 1, 12.0)",
  "    assert b.position == 1",
  "    assert b.cash == 92.0",
  "",
  "",
  "def test_invalid_side_qty_price():",
  "    b = Broker(cash=100.0)",
  "    with pytest.raises(ValueError):",
  "        b.market_order('hold', 1, 10.0)",
  "    with pytest.raises(ValueError):",
  "        b.market_order('buy', 0, 10.0)",
  "    with pytest.raises(ValueError):",
  "        b.market_order('buy', 1, 0.0)",
  "",
  "",
  "def test_insufficient_cash():",
  "    b = Broker(cash=5.0)",
  "    with pytest.raises(ValueError):",
  "        b.market_order('buy', 1, 10.0)",
  "",
  "",
  "def test_insufficient_shares():",
  "    b = Broker(cash=100.0)",
  "    with pytest.raises(ValueError):",
  "        b.market_order('sell', 1, 10.0)",
  "",
  "",
  "def test_equity():",
  "    b = Broker(cash=100.0)",
  "    b.market_order('buy', 2, 10.0)",
  "    assert b.equity(12.0) == 104.0"
)

# tests/test_engine.py
Write-File ".\tests\test_engine.py" @(
  "import pandas as pd",
  "import pytest",
  "",
  "from trading.subject import MarketDataSubject",
  "from trading.broker import Broker",
  "from trading.engine import Engine",
  "",
  "",
  "class ThresholdStrategy:",
  "    def __init__(self, lo: float, hi: float):",
  "        self.lo = float(lo)",
  "        self.hi = float(hi)",
  "        self.last_signal = 0",
  "",
  "    def update(self, price: float) -> None:",
  "        p = float(price)",
  "        if p > self.hi:",
  "            self.last_signal = 1",
  "        elif p < self.lo:",
  "            self.last_signal = -1",
  "        else:",
  "            self.last_signal = 0",
  "",
  "",
  "def test_engine_places_orders_and_returns_equity():",
  "    subject = MarketDataSubject()",
  "    strategy = ThresholdStrategy(lo=99.0, hi=101.0)",
  "    broker = Broker(cash=1_000)",
  "    engine = Engine(subject, strategy, broker, trade_qty=1)",
  "",
  "    prices = pd.Series([100.0, 102.0, 102.0, 98.0, 100.0])",
  "    equity = engine.run(prices)",
  "",
  "    assert broker.position == 1",
  "    assert broker.cash == 894.0",
  "    assert equity == 894.0 + 1 * 100.0",
  "",
  "",
  "def test_engine_empty_prices_raises():",
  "    subject = MarketDataSubject()",
  "    strategy = ThresholdStrategy(lo=0.0, hi=1.0)",
  "    broker = Broker(cash=100.0)",
  "    engine = Engine(subject, strategy, broker)",
  "",
  "    with pytest.raises(ValueError):",
  "        engine.run(pd.Series([], dtype=float))",
  "",
  "",
  "def test_engine_propagates_subject_notification_error():",
  "    class BadObs:",
  "        def update(self, price: float) -> None:",
  "            raise RuntimeError('fail')",
  "",
  "        @property",
  "        def last_signal(self) -> int:",
  "            return 0",
  "",
  "    subject = MarketDataSubject()",
  "    broker = Broker(cash=100.0)",
  "    bad = BadObs()",
  "    engine = Engine(subject, bad, broker)",
  "",
  "    with pytest.raises(RuntimeError):",
  "        engine.run(pd.Series([100.0, 101.0]))"
)

Write-Host "Files created."

# venv with Python 3.11
Write-Host "Creating venv (.venv) using Python 3.11..."
& py -3.11 -m venv .venv

Write-Host "Activating venv..."
& .\.venv\Scripts\Activate.ps1

Write-Host "Installing deps..."
python -m pip install --upgrade pip
pip install -r .\requirements.txt

Write-Host "Running tests..."
pytest

Write-Host "Running coverage..."
coverage run -m pytest -q
coverage report --fail-under=90 -m

Write-Host "DONE." -ForegroundColor Green
